import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: {
    default: "Next.js tutorial - Codevolution",
    template: "%s | Codevolution",
    absolute: "",
  },
  description: "Generated by Next.js"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div style={{
          backgroundColor: 'skyblue',
          height: '100px',
          marginBottom: '40px',
          textAlign: 'center',
          fontSize: '40px'
        }} >
          <h1 >Header</h1>
        </div>
        {children}
        <div style={{
          backgroundColor: 'grey',
          height: '100px',
          marginBottom: '40px',
          textAlign: 'center',
          fontSize: '40px'
        }} >
          <h1>Footer</h1>
        </div>
      </body>
    </html>
  );
}
